services:
  backend:
    build: .
    container_name: roles_backend
    restart: always
    ports:
      - "3000:3000"         # Porta do backend acess√≠vel na rede local
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 0411
      DB_NAME: roles_db
      JWT_SECRET: minha_chave_secreta_segura
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8
    container_name: roles_mysql
    restart: always
    ports:
      - "3308:3306"         # Porta exposta para o host (acesso local)
    environment:
      MYSQL_ROOT_PASSWORD: 0411
      MYSQL_DATABASE: roles_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
